feat(rust): implement `TokenMintTransaction`
hiero-ledger/hiero-sdk-rust pull request #184
Opened 2022-06-16 20:29 UTC by willparks

Signed-off-by: Will Parks <will.parks@launchbadge.com>

**Description**:

- Implements `TokenMintTransaction`

**Related issue(s)**:

Fixes #44

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-06-16 20:30 UTC, willparks commented on sdk/rust/src/token/token_mint_transaction.rs
> +    pub fn metadata(&mut self, metadata: impl Into<Vec<Vec<u8>>>) -> &mut Self {
Was unsure about this - is `impl Into<Vec<Vec<u8>>>` correct here?

2022-06-16 23:41 UTC, mehcode requested changes

2022-06-16 23:41 UTC, mehcode commented on sdk/rust/src/token/token_mint_transaction.rs
> +    pub fn metadata(&mut self, metadata: impl Into<Vec<Vec<u8>>>) -> &mut Self {
@willparks, no - for binary data, you generally want to say 

```
impl AsRef<[u8]>
```

but for a _list_ of binary data you can say

```rust
pub fn metadata<Bytes>(&mut self, metadata: impl IntoIterator<Item = Bytes>) -> &mut Self
where Bytes: AsRef<[u8]>
{
  let metadata = metadata.into_iter().map(|bytes| bytes.as_ref().to_vec()).collect();
```

2022-06-17 00:17 UTC, willparks commented on sdk/rust/src/token/token_mint_transaction.rs
> +    pub fn metadata(&mut self, metadata: impl Into<Vec<Vec<u8>>>) -> &mut Self {
Ah, thank you! Updating now.

2022-06-17 00:25 UTC, merged