feat(rust): implement `TokenNftInfoQuery`
hiero-ledger/hiero-sdk-rust pull request #186
Opened 2022-06-17 22:36 UTC by willparks

Signed-off-by: Will Parks <will.parks@launchbadge.com>

**Description**:

- Implements `TokenNftInfoQuery`

**Related issue(s)**:

Fixes #45

**Notes for reviewer**:

Couldn't find a protobuf for `LedgerId`, and saw it was something commented out elsewhere as well. I added it into `TokenNftInfoResponse` and commented it out as a todo item for now.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-06-21 23:44 UTC, mehcode commented on sdk/rust/src/token/nft_id.rs
> +        write!(f, "{}.{}.{}/{}", self.token_id.shard, self.token_id.realm, self.token_id.num, self.serial_number)
```suggestion
        write!(f, "{}/{}", self.token_id, self.serial_number)
```

2022-06-21 23:45 UTC, mehcode commented on sdk/rust/src/token/nft_id.rs
> +            return Err(Error::basic_parse("unexpected NftId format - expected [token_id]/[serial_number] or [token_id]@[serial_number]"))
@danielakhterov @willparks Where did the `@` format come from?

2022-06-21 23:46 UTC, mehcode commented on sdk/rust/src/token/token_nft_info_response.rs
> +    pub spender_id: AccountAddress,
As this is a response, let's let this be `Option` and remove the `pb_getf` call (use `.map`)

2022-06-21 23:46 UTC, mehcode commented on sdk/rust/src/token/token_nft_info_response.rs
> +    pub account_id: AccountAddress,
This should be `AccountId`. `AccountAddress` is never _returned_ as a response from Hedera.

2022-06-21 23:47 UTC, mehcode commented on sdk/rust/src/token/token_nft_info_query.rs
> +    pub fn nft_id(&mut self, nft_id: impl Into<NftId>) -> &mut Self {
@danielakhterov is there anything big about this we wanted to rethink? or are we generally happy about "NFT ID" 

Do we need methods on `TokenId` ?

2022-06-21 23:49 UTC, willparks commented on sdk/rust/src/token/nft_id.rs
> +            return Err(Error::basic_parse("unexpected NftId format - expected [token_id]/[serial_number] or [token_id]@[serial_number]"))
I picked it up from the JS SDK -- https://github.com/hashgraph/hedera-sdk-js/blob/64944afdeeab352609d32203153d0ced3ccaf456/src/token/NftId.js#L54

2022-06-22 00:04 UTC, janaakhterov commented on sdk/rust/src/token/token_nft_info_query.rs
> +    pub fn nft_id(&mut self, nft_id: impl Into<NftId>) -> &mut Self {
I feel like we can remove the methods on `TokenId` because the `NftId` constructor already exists. However, even though I'm not the biggest fan of `NftId` I think we should keep it over having `TokenId` and `serialNumber` as separate parameters.

2022-06-22 00:05 UTC, janaakhterov commented on sdk/rust/src/token/nft_id.rs
> +            return Err(Error::basic_parse("unexpected NftId format - expected [token_id]/[serial_number] or [token_id]@[serial_number]"))
The `@` I think came first, but then we changed it because it was too confusing with `TransactionId`. JS needs to fix this :facepalm:

2022-06-22 08:51 UTC, mehcode commented on sdk/rust/src/token/token_nft_info_query.rs
> +    pub fn nft_id(&mut self, nft_id: impl Into<NftId>) -> &mut Self {
I'm fine with keeping `NftId`, if only because of how easy they are to construct. `NftId::new(token_id, 20)` and we should probably make it `(token_id, 20).into()` as well.

2022-06-27 22:05 UTC, janaakhterov requested changes

2022-06-27 22:05 UTC, janaakhterov commented on sdk/rust/src/token/token_nft_info_response.rs
> +            .flatten();
Hmm, I feel like we should error here instead of silently setting spender to 0
```suggestion
        let spender_id = nft.spender_id
            .map(AccountId::from_protobuf)
            .transpose()?;
```

2022-06-28 17:51 UTC, willparks commented on sdk/rust/src/token/token_nft_info_response.rs
> +            .flatten();
Ah, thanks! I wasn't fully aware of how `.map()` treated `None` values coming in (looking at the source explained this better than the docs). This makes perfect sense, will update.

2022-06-30 00:31 UTC, janaakhterov approved these changes

2022-06-30 00:31 UTC, merged