feat: add Hbar
hiero-ledger/hiero-sdk-rust pull request #207
Opened 2022-09-21 02:13 UTC by Sean-Tedrow-LB

Signed-off-by: Sean Tedrow <sean.tedrow@launchbadge.com>

Need to add some unit tests, and make use of `Hbar` throughout the SDK.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-09-21 19:59 UTC, izik1 requested changes
Most of the review comments contain nits that you can feel free to ignore if you have an argument against them. However there _are_ a couple changes that still need to be made (other than adding tests)

2022-09-21 19:59 UTC, izik1 commented on sdk/rust/src/hbar.rs
> +     */
Standardized formatting of doc comments would be something like
```suggestion
     /// The atomic (smallest) unit of [`Hbar`], used natively by the Hedera network.
     /// 
     /// It is equivalent to `1 / 100_000_000`  [`Hbar`].
```
The change on the last line is arguably style, but I'd note that the `code` type formatting makes it nice to understand.

2022-09-21 19:59 UTC, izik1 commented on sdk/rust/src/hbar.rs
> +     */
see above

2022-09-21 19:59 UTC, izik1 commented on sdk/rust/src/hbar.rs
> +     */
see above

2022-09-21 19:59 UTC, izik1 commented on sdk/rust/src/hbar.rs
> +     */
```suggestion
    /// The base unit of [`Hbar`], equivalent to 100 million [`Tinybar`](Self::Tinybar).
```

2022-09-21 19:59 UTC, izik1 commented on sdk/rust/src/hbar.rs
> +     */
see above, additionally, `1000` is... Clearer than `1 thousand`, I feel.

2022-09-21 19:59 UTC, izik1 commented on sdk/rust/src/hbar.rs
> +     */
see above

2022-09-21 19:59 UTC, izik1 commented on sdk/rust/src/hbar.rs
> +     */
I think the `2<sup>63` is actually fine here, although, maybe \`2^63\` would be better because of the code-fencing, but, I don't have a strong opinion there

2022-09-21 19:59 UTC, izik1 commented on sdk/rust/src/hbar.rs
> +    pub fn tinybars(self) -> Tinybar {
```suggestion
    #[must_use]
    pub const fn tinybars(self) -> Tinybar {
```

2022-09-21 19:59 UTC, izik1 commented on sdk/rust/src/hbar.rs
> +    pub fn symbol(self) -> &'static str {
```suggestion
    #[must_use]
    pub const fn symbol(self) -> &'static str {
```

2022-09-21 19:59 UTC, izik1 commented on sdk/rust/src/hbar.rs
> +        write!(f, "{}", self.symbol())
`Formatter::write_str` is decently more performant and slightly smaller than `write!()` because of formatting machinery
```suggestion
        f.write_str(self.symbol);
```

2022-09-21 19:59 UTC, izik1 commented on sdk/rust/src/hbar.rs
> +            _ => Err(Error::basic_parse(format!("Given string \"{}\" was not recognized as an Hbar unit symbol", s)))
```suggestion
            _ => Err(Error::basic_parse(format!("Given string `{s}` was not recognized as an Hbar unit symbol")))
```

2022-09-21 19:59 UTC, izik1 commented on sdk/rust/src/hbar.rs
> +        let parts: Vec<&str> = s.splitn(2, " ").collect();
https://doc.rust-lang.org/std/primitive.str.html#method.split_once is stable nowadays, so, you can do... This... I hesitate to call it magic, because it isn't hackery.
```rust
let (amount, unit) = s.split_once(' ').unzip();
let amount = amount.unwrap_or(s);
```
(`unzip` basically does `Some((a, b)) => (Some(a), Some(b))`)

2022-09-21 19:59 UTC, izik1 commented on sdk/rust/src/hbar.rs
> +        };
If you go with the first comment in this function, this would turn into
Option 1. (my favorite)
```rs
let unit = unit.map(HbarUnit::from_str).transpose()?.unwrap_or(HbarUnit::Hbar);
```

Option 2. (I don't really like because that's a really funky invocation of `map_or`)
```rs
let unit = unit.map_or(Ok(HbarUnit::Hbar), HbarUnit::from_str)?;
```

Option 3. (which is basically just what you have there, but using `match`)
```rs
let unit = match unit {
    Some(it) => HbarUnit::from_str(it)?,
    None => HbarUnit::Hbar
}
```

Option 4. (What you have, but using `if let`)
```rs
let unit = if let Some(it) = unit {
    HbarUnit::from_str(it)?
} else {
    HbarUnit::Hbar
};
```

If you _don't_ end up using `split_once`, I'd recommend using `parts.get(1)` which gives you an `Option`, and makes the above Options applicable. (using a length check and then getting an element if it exists, in order to avoid an index oob panic is less idiomatic than any of the above)

2022-09-21 19:59 UTC, izik1 commented on sdk/rust/src/lib.rs
> +mod hbar;
can't put this comment anywhere else in this file, but this isn't accessible to the outside world until you
```rs
pub use hbar::{
    Hbar,
    HbarUnit,
    Tinybar,
};
```
(Put it anywhere with the other ones, then use `cargo fmt` to sort it, rather than trying to find the right spot)

2022-09-21 19:59 UTC, izik1 commented on sdk/rust/src/hbar.rs
> +        if self.to_tinybars() > -10_000 && self.to_tinybars() < 10_000 {
`if self.to_tinybars().abs() < 10_000`?

2022-09-21 19:59 UTC, izik1 commented on sdk/rust/src/hbar.rs
> +        let amount: Decimal = parts[0].parse().map_err(|err| Error::basic_parse(err))?;
```suggestion
        let amount: Decimal = parts[0].parse().map_err(Error::basic_parse)?;
```

2022-09-21 19:59 UTC, izik1 commented on sdk/rust/src/hbar.rs
> +pub struct Hbar(i64);
I'd recommend moving either this struct down near the corresponding `impl` block, or moving the `impl` block up to here

2022-09-21 19:59 UTC, izik1 commented on sdk/rust/src/hbar.rs
> +pub struct Hbar(i64);
I'd also recommend adding a `Debug` impl that just calls the `Display` impl, something like (note the extra double quotes, because, for `Display` we want `1.2 ℏ`, but for `Debug`, strings are surrounded by quotes, so, `"1.2 ℏ"`)
```rs
impl Debug for PrivateKey {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        write!(f, "\"{self}\"")
    }
}
```

2022-09-21 20:00 UTC, izik1 commented on sdk/rust/src/hbar.rs
> +     * Equivalent to 1 billion hbar or 100 quadillion tinybar.
Right, somehow forgot this one, `quadillion` -> `quadrillion`

2022-09-21 21:28 UTC, Sean-Tedrow-LB commented on sdk/rust/src/hbar.rs
> +        if self.to_tinybars() > -10_000 && self.to_tinybars() < 10_000 {
This matches [the implementation in the Java SDK](https://github.com/hashgraph/hedera-sdk-java/blob/988c92ea3e8f1b3965fd04cf724458e4ce6a44b3/sdk/src/main/java/com/hedera/hashgraph/sdk/Hbar.java#L227-L233)

2022-09-21 21:29 UTC, Sean-Tedrow-LB commented on sdk/rust/src/hbar.rs
> +        if self.to_tinybars() > -10_000 && self.to_tinybars() < 10_000 {
Nah.

2022-09-21 21:29 UTC, Sean-Tedrow-LB commented on sdk/rust/src/hbar.rs
> +        };
I like option 2

2022-09-21 21:36 UTC, Sean-Tedrow-LB commented on sdk/rust/src/hbar.rs
> +        let parts: Vec<&str> = s.splitn(2, " ").collect();
Cargo complains that `unzip()` is not stable

2022-09-21 23:17 UTC, izik1 approved these changes, later dismissed

2022-09-23 00:52 UTC, mehcode commented on sdk/rust/src/hbar.rs
> +    SerializeDisplay,
@Sean-Tedrow-LB We need to serialize/deserialize as a numerical _tinybar_ value.

2022-09-23 00:58 UTC, mehcode commented on sdk/rust/src/token/custom_fees.rs
>  use crate::{
Just as a note - we need to rewrite the custom fee types here to match what they are in Swift/Java/etc.

2022-09-23 17:15 UTC, skyler-lb approved these changes

2022-09-23 19:43 UTC, merged