feat: add checksums
hiero-ledger/hiero-sdk-rust pull request #354
Opened 2022-12-02 04:54 UTC by Sean-Tedrow-LB

Signed-off-by: Sean Tedrow <sean.tedrow@launchbadge.com>

Still need to add documentation and automatic checksum validation.

2022-12-02 20:00 UTC, izik1 requested changes

2022-12-02 20:00 UTC, izik1 commented on sdk/rust/src/account/account_id.rs
> +            panic!("to_string_with_checksum cannot be applied to AccountId with alias")
An argument can be made that libraries shouldn't panic

2022-12-02 20:00 UTC, izik1 commented on sdk/rust/src/client/mod.rs
> +    pub fn set_ledger_id(&self, ledger_id: Option<LedgerId>) {
Is there ever a time where you'd want to set the ledger ID to none?

2022-12-02 20:00 UTC, izik1 commented on sdk/rust/src/contract/contract_id.rs
> -        let expecting = || {
Why the change? AFAIK this basically just reverts a change I made earlier>

2022-12-02 20:00 UTC, izik1 commented on sdk/rust/src/entity_id.rs
> +        let w = 31 as usize; // Sum s of digit values weights them by powers of w. Should be coprime to p5.
```suggestion
        const P3: usize = 26 * 26 * 27; // 3 digits in base 26
        const P5: usize = 26 * 26 * 26 * 26 * 26; // 5 digits in base 26
        const M: usize = 1_000_003; // min prime greater than a million. Used for the final permutation.
        const W: usize = 31; // Sum s of digit values weights them by powers of w. Should be coprime to p5.
```

2022-12-02 20:00 UTC, izik1 commented on sdk/rust/src/entity_id.rs
> +        let h = [ledger_id.to_bytes(), vec![0u8, 0u8, 0u8, 0u8, 0u8, 0u8]].concat();
```suggestion
        let h = [ledger_id.to_bytes(), vec![0u8; 6]].concat();
```

I'd argue against creating a `Vec` here at all, but...

2022-12-02 20:00 UTC, izik1 commented on sdk/rust/src/entity_id.rs
> +            answer[i] = 'a' as u8 + ((c % 26) as u8);
```suggestion
            answer[i] = b'a' + ((c % 26) as u8);
```

2022-12-02 20:00 UTC, izik1 commented on sdk/rust/src/entity_id.rs
> +        let mut answer = [0_u8, 0_u8, 0_u8, 0_u8, 0_u8];
```suggestion
        let mut answer = [0_u8; 5];
```

2022-12-02 20:00 UTC, izik1 commented on sdk/rust/src/entity_id.rs
> +        for (i, digit) in d.into_iter().enumerate() {
You're collecting `d` into a `Vec` and then immediately iterating over it again, instead, save the iterator (`let mut d = entity_id_string.chars().map(...);` and instead of calling `into_iter` just call enumerate

2022-12-02 20:00 UTC, izik1 commented on sdk/rust/src/entity_id.rs
> +                panic!("Can't validate checksum without knowing which ledger the ID is for.  Ensure client's ledger ID is set.")
This function returns an error, so, an error here would be best

2022-12-02 20:00 UTC, izik1 commented on sdk/rust/src/entity_id.rs
> +        let outer_parts: Vec<&str> = s.split("-").collect();
I'm pretty sure you're trying to get the checksum here, so, `split_once` would be perfect here

2022-12-02 20:00 UTC, izik1 commented on sdk/rust/src/error.rs
> +        expected_checksum: Checksum,
This probably should show the expected checksum?

2022-12-02 20:00 UTC, izik1 commented on sdk/rust/src/error.rs
> +    #[error("Entity ID {shard}.{realm}.{num}-{present_checksum} was incorrect.")]
Error messages can be shown inside other error messages, so, `EntityId` or `entity ID` and no period

2022-12-02 21:01 UTC, Sean-Tedrow-LB commented on sdk/rust/src/account/account_id.rs
> +            panic!("to_string_with_checksum cannot be applied to AccountId with alias")
Go talk to Ryan

2022-12-02 21:02 UTC, Sean-Tedrow-LB commented on sdk/rust/src/client/mod.rs
> +    pub fn set_ledger_id(&self, ledger_id: Option<LedgerId>) {
Yes, if this is a custom ledger.  The SDK needs to be able to interact with any deployment of hedera, not just the official one.

2022-12-02 21:05 UTC, Sean-Tedrow-LB commented on sdk/rust/src/contract/contract_id.rs
> -        let expecting = || {
`from_str()` needs to handle checksums.  The checksum reading code is in `EntityId::from_str()`.  `AccountId::from_str()` was similar (with its `alias` field), but was implemented in a nice way that made this change easy.  I decided to modify `ContractId::from_str()` to be structured similarly to `AccountId::from_str()`.

2022-12-02 21:10 UTC, Sean-Tedrow-LB commented on sdk/rust/src/entity_id.rs
> +                panic!("Can't validate checksum without knowing which ledger the ID is for.  Ensure client's ledger ID is set.")
Talk to Ryan

2022-12-02 21:37 UTC, Sean-Tedrow-LB commented on sdk/rust/src/error.rs
> +        expected_checksum: Checksum,
Actually, there's really no point showing it.  If the checksum is wrong, it _should_ mean that the ID was mis-typed in general, and "correcting" the checksum is not the solution.

2022-12-02 21:38 UTC, Sean-Tedrow-LB commented on sdk/rust/src/error.rs
> +        expected_checksum: Checksum,
Including the expected checksum in the error data is good for debugging, but I am worried (I think justifiably) that people are just going to print the error message to a hypothetical user.

2022-12-03 02:01 UTC, izik1 approved these changes, later dismissed

2022-12-03 04:20 UTC, izik1 approved these changes

2022-12-05 22:00 UTC, merged