Remove two Dentons proxies
hiero-ledger/hiero-sdk-rust pull request #737
Opened 2023-11-10 20:18 UTC by dalvizu

**Description**:
Per Dentons these are seeing very little traffic and they would like to delete them to remove costs. These must be removed from docs and address books first to avoid disruption to the network.

**Related issue(s)**:

https://github.com/hashgraph/hedera-docs/pull/496

**Notes for reviewer**:
N/A

**Checklist**

- [X] Documented (Code comments, README, etc.)
- [X] Tested (unit, integration, etc.)

2023-11-13 17:40 UTC, SimiHunjan approved these changes

2023-11-13 19:32 UTC, RickyLB requested changes
@dalvizu Go ahead and use `cargo +nightly fmt` to pass the format CI.

2023-11-14 15:09 UTC, dalvizu commented
Hi @RickyLB  - I am not a rust developer and it will take me time to get this in place. I'm in DevOps management so I don't exactly have a lot of time, either. The linting step is unrelated to my failures. If you see this as blocking can you please add any formatting you'd like to see?

2023-11-16 20:42 UTC, RickyLB approved these changes

2023-11-16 20:48 UTC, merged