feat: add signer nonce
hiero-ledger/hiero-sdk-rust pull request #760
Opened 2024-02-17 01:33 UTC by RickyLB

**Description**:

- Updated protobufs
- Added `signer_nonce`
- 

**Related issue(s)**:
- https://github.com/hashgraph/hedera-sdk-rust/issues/758

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-03-09 02:12 UTC, izik1 requested changes

2024-03-09 02:12 UTC, izik1 commented on src/ethereum/ethereum_data.rs
> +
```suggestion
```

2024-03-11 21:43 UTC, Sheng-Long approved these changes

2024-03-12 02:03 UTC, izik1 approved these changes

2024-03-12 02:04 UTC, merged